---
title: "Mitochondria from osteolineage cells regulate myeloid cell-mediated bone resorption"
author: "Jeff Walker"
date: '23 Jun 2024'
date-modified: "`r Sys.Date()`"
categories: ["linear mixed model", "random intercept", "CRDS", "nested ANOVA", "ggplot"]
description: "xxx"
draft: true
format: 
  html: 
    toc: true 
    toc-location: right
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: inline
freeze: auto

---

## Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# wrangling packages
library(here) # here makes a project transportable
library(janitor) # clean_names
library(readxl) # read excel, duh!
library(writexl) # write excel, duh!
library(data.table) # magical data frames
library(magrittr) # pipes
library(stringr) # string functions
library(forcats) # factor functions

# analysis packages
library(emmeans) # the workhorse for inference
library(nlme) # gls and some lmm
library(lme4) # linear mixed models
library(lmerTest) # linear mixed model inference
library(afex) # ANOVA linear models
library(glmmTMB) # generalized linear models
library(MASS) # negative binomial and some other functions
library(car) # model checking and ANOVA
library(DHARMa) # model checking
library(mvtnorm)
library(MHTdiscrete) # sidak

# graphing packages
library(ggsci) # color palettes
library(ggpubr) # publication quality plots
library(ggforce) # better jitter
library(cowplot) # combine plots
library(knitr) # kable tables
library(kableExtra) # kable_styling tables

# ggplot_the_model.R packages not loaded above
library(insight)
library(lazyWeave)

# use here from the here package
here <- here::here
# use clean_names from the janitor package
clean_names <- janitor::clean_names
# use transpose from data.table
transpose <- data.table::transpose

# load functions used by this text written by me
# ggplot_the_model.R needs to be in the folder "R"
# if you didn't download this and add to your R folder in your
# project, then this line will cause an error
source_path <- here("R", "ggplot_the_model.R")
source(source_path)

data_folder <- "data from"
image_folder <- "images"
output_folder <- "output"
```

## Import and Wrangle


```{r fig-3g-import, message=FALSE, warning=FALSE}
data_from <- "Mitochondria from osteolineage cells regulate myeloid cell-mediated bone resorption"
file_name <- "ncomms-source-data files OSSENI et al.xlsx"
file_path <- here(data_folder, data_from, file_name)

fig2s_wide <- read_excel(file_path,
                    sheet = "Figure 2",
                    range = "E138:J186",
                    col_names = FALSE) |>
  data.table()
mouse_id <- paste("mouse", 1:6, sep = "_")
treatment_levels <- c("MDX-Veh", "MDX-TubA")
mouse_treatment <- paste(rep(treatment_levels, each = 3), mouse_id)
colnames(fig2s_wide) <- mouse_treatment
fig2s <- melt(fig2s_wide,
              measure.vars = mouse_treatment,
              variable.name = "mouse_treatment",
              value.name = "fibrotic_area") |>
  na.omit()
fig2s[, c("treatment", "mouse_id") := tstrsplit(mouse_treatment, " ")]
fig2s[, treatment := factor(treatment, levels = treatment_levels)]

file_out_name <- "fig2s-CRDS-Pharmacological inhibition of HDAC6 improves muscle phenotypes in dystrophin-deficient mice by downregulating TGF-β via Smad3 acetylation.xlsx"
fileout_path <- here(data_folder, data_from, file_out_name)
write_xlsx(fig2s, fileout_path)
```
